### PR TITLE
Fix to support windows

### LINKED ISSUE #91: Support Windows
Are your examples suppose to work on a windows computer? I have no problem getting them running on a mac but when I try  on windows with the same gems and ruby 2.3.0 it gives me this error every time:

`test.rb:5: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
E, [2016-05-12T17:11:19.461844 #2396] ERROR -- : Actor crashed!
ThreadError: deadlock; recursive locking
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/selector.rb:37:in`synchronize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/selector.rb:37:in `deregister'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/lib/nio/monitor.rb:52:in`close'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:52:in `wait'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:21:in`wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io.rb:54:in `wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:28:in`wait_readable'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:44:in `rescue in recvfrom'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/udp_socket.rb:35:in`recvfrom'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/dns_resolver.rb:45:in `resolve'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:101:in`create_socket'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/tcp_socket.rb:53:in `initialize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in`new'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/socket.rb:39:in `new'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:80:in`build_socket'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:33:in `run_loop'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/concurrency/celluloid.rb:29:in`connect!'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in`dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in`block in dispatch'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in`block in task'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in`block in create'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in`block in cleanup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in`cleanup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in`handle_crash'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in`run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in`block in initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in`block in instantiate'
        from (celluloid):0:in `remote procedure call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in`value'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.7.2/lib/slack/real_time/client.rb:51:in`start!'
        from test.rb:41:in `<main>'
`

### PR DESCRIPTION
**Pull request by leifcr**
The syntax for grep/awk/sed is problematic under cmdline on windows

This removes the dependency of awk/grep/sed., openssldir is parsed in ruby instead.

This can close #91, since everything else works as it should on Windows.

### CODE REVIEW

File: lib/slack/web/config.rb [hunk 1]
```diff
@@ -21,15 +21,21 @@ module Config
       def reset
         self.endpoint = 'https://slack.com/api/'
         self.user_agent = "Slack Ruby Client/#{Slack::VERSION}"
-        self.ca_path = `openssl version -a | grep OPENSSLDIR | awk '{print $2}'|sed -e 's/\"//g'`
-        self.ca_file = "#{ca_path}/ca-certificates.crt"
+        self.ca_path = openssl_ca_path if ca_path.nil?
```
Comment (mikz) [inline lib/slack/web/config.rb]: Can't this be just using `OpenSSL::X509::DEFAULT_CERT_DIR` and `OpenSSL::X509::DEFAULT_CERT_FILE` ?

Comment (mikz) [reply lib/slack/web/config.rb]: This (openssl version -a) does not work on MacOS Sierra (10.12) also.

My `OPENSSLDIR` is `/System/Library/OpenSSL`. 

But `/System/Library/OpenSSL/ca-certificates.crt` does not exist.


When using system ruby then  `OpenSSL::X509::DEFAULT_CERT_FILE` points to `/System/Library/OpenSSL/cert.pem` which also does not exist.

But at least it works with own compiled ruby.

Also it is reasonable to use `SSL_CERT_DIR` and `SSL_CERT_FILE` env variables before the openssl default. (like https://github.com/mikz/httpclient/blob/ba21d0d44c9f5f4602c7fc151f7c24f827480361/lib/httpclient/ssl_config.rb#L418-L419) 

As those are used by OpenSSL to set custom cert dir/path.

Comment (leifcr) [reply lib/slack/web/config.rb]: I'll change the pr to use OpenSSL::X509::DEFAULT_CERT_DIR and OpenSSL::X509::DEFAULT_CERT_FILE, since that works on nix, win and osx.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,5 @@
 ### 0.9.2 (Next)
-
+* [#163](https://github.com/slack-ruby/slack-ruby-client/pull/164): Use OpenSSL::X509::DEFAULT_CERT_DIR and OpenSSL::X509::DEFAULT_CERT_FILE for default ca_cert and ca_file [@leifcr](https://github.com/leifcr)
```
Comment (mikz) [inline CHANGELOG.md]: would be good to highlight code constants as code with \`CODE\`

File: lib/slack/web/config.rb [hunk 3]
```diff
@@ -1,3 +1,4 @@
+require 'openssl'
```
Comment (mikz) [inline lib/slack/web/config.rb]: This would make OpenSSL hard dependency. 

Might be better to wrap it in a block and rescue `LoadError`.

File: lib/slack/web/config.rb [hunk 4]
```diff
@@ -21,8 +22,8 @@ module Config
       def reset
         self.endpoint = 'https://slack.com/api/'
         self.user_agent = "Slack Ruby Client/#{Slack::VERSION}"
-        self.ca_path = `openssl version -a | grep OPENSSLDIR | awk '{print $2}'|sed -e 's/\"//g'`
-        self.ca_file = "#{ca_path}/ca-certificates.crt"
+        self.ca_path = OpenSSL::X509::DEFAULT_CERT_DIR
```
Comment (mikz) [inline lib/slack/web/config.rb]: If `OpenSSL` is not defined (guess we don't want hard dependency) then this would crash. So this can be done as

```ruby
self.ca_path = OpenSSL::X509::DEFAULT_CERT_DIR if defined?(OpenSSL)
```

**Comment by leifcr** [comment]
@mikz I added test for OpenSSL, so that vars are set to nil if missing.

File: lib/slack/web/faraday/connection.rb [hunk 5]
```diff
@@ -11,7 +11,7 @@ def connection
 
           options[:headers]['User-Agent'] = user_agent if user_agent
           options[:proxy] = proxy if proxy
-          options[:ssl] = { ca_path: ca_path, ca_file: ca_file }
+          options[:ssl] = { ca_path: ca_path, ca_file: ca_file } unless ca_path.nil? || ca_file.nil?
```
Comment (mikz) [inline lib/slack/web/faraday/connection.rb]: This could be tricky.

Do both options have to be specified? Can't just one do the trick? I think one certificate chain can work just fine as well as just the cert directory.

So this could be nicer as `if ca_path || ca_file`. Unless with `||` can be evil.

**Comment by mikz** [comment]
@leifcr great change! I commented one last time https://github.com/slack-ruby/slack-ruby-client/pull/164#discussion_r138360857 to clarify the ca info assignment.

Then it would get mine 👍 Good job 🥇

File: CHANGELOG.md [hunk 6]
```diff
@@ -1,5 +1,5 @@
 ### 0.9.2 (Next)
-
```
Comment (dblock) [inline CHANGELOG.md]: Put back the line, please.

File: CHANGELOG.md [hunk 7]
```diff
@@ -1,5 +1,5 @@
...
+* [#163](https://github.com/slack-ruby/slack-ruby-client/pull/164): Use `OpenSSL::X509::DEFAULT_CERT_DIR` and `OpenSSL::X509::DEFAULT_CERT_FILE` for default ca_cert and ca_file [@leifcr](https://github.com/leifcr)
```
Comment (dblock) [inline CHANGELOG.md]: Make this in the same format as everything else, needs a `-` before your name and a `.` at the end.

File: lib/slack/web/config.rb [hunk 8]
```diff
@@ -1,3 +1,8 @@
+begin
+  require 'openssl'
+rescue LoadError # rubocop:disable Lint/HandleExceptions
+end
```
Comment (dblock) [inline lib/slack/web/config.rb]: I don't think this is a great place to put this, `lib/slack-ruby-client.rb` is better, it has all the `require`.

**Comment by dblock** [comment]
Made some minor comments. Thanks for making this happen @leifcr. Do you think we can get a Windows CI somewhere?

**Comment by mikz** [comment]
@dblock seen https://www.appveyor.com a few times.

File: lib/slack/web/config.rb (hunk 8 above)
Comment (leifcr) [reply lib/slack/web/config.rb]: @dblock Agree. Will move it there.

File: lib/slack/web/faraday/connection.rb (hunk 5 above)
Comment (leifcr) [reply lib/slack/web/faraday/connection.rb]: agree. if ca_path || ca_file is better. And only one needs to be present.

**Comment by leifcr** [comment]
@mikz and @dblock Thanks for feedback. Appveyor supports ruby: https://www.appveyor.com/docs/lang/ruby/

**Comment by dblock** [comment]
Run `rubocop -a ; rubocop --auto-gen-config` to fix CI.

**Comment by dblock** [comment]
@leifcr If you want to PR Appveyor support (appveyor.yml, etc.), I can help enable if something needs to be done here. I used it in https://github.com/Waffle/waffle and https://github.com/resourcelib/resourcelib :)

**Comment by leifcr** [comment]
@dblock I'll create a new branch for Appveyor and do a separate PR For that.

**Comment by dblock** [comment]
Merged, thanks.

**Comment by leifcr** [comment]
Thanks
